### ISSUE TITLE
ISSUE: TM Function does not handle inner reference response

### ISSUE THREAD

**Issue by nkreiger** [triggermesh/aws-custom-runtime#45]
Per the triggermesh [docs](url) ->

"Functions may be used to implement custom event flow logic"

Expectation:

Using a `function` to do a custom/complex transformation before reaching an inner processing `ksvc` will perform the transformation and return the result of the `ksvc`.

Reality:

It does the custom transformation, but the response is nil.

https://github.com/triggermesh/aws-custom-runtime/blob/main/pkg/sender/sender.go#L56

Simple Example

```yaml
# perform modification (only user code part) to attestation input
apiVersion: extensions.triggermesh.io/v1alpha1
kind: Function
metadata:
  name: custom-tsf
  namespace: default
spec:
  runtime: python
  public: true
  entrypoint: main
  sink:
    ref:
      name: example-inner
      namespace: default
      kind: Service
      apiVersion: serving.knative.dev/v1
  code: |
    def main(payload, context):
        payload['metdata'] = 'some change'

        return payload
```

hitting this function will always return nil, because it sends to an inner `ksvc`, I do not think you should have to create a sinkbinding or assume the broker for the inner ksvc each time to return the event...I think it should match the flow of a transformation which returns it to the same broker the transformation reads from (same with a filter).

It just seems like the function is unique in this regard, and it breaks expectations.

**Comment by antoineco** [comment]
@nkreiger I would suggest using the building blocks of Knative eventing here, and fronting the Kn Service with a Channel to make that flow truly asynchronous.

1. In your transformation, send to the Channel, not the Kn Service.
1. Create a Subscription that sends messages from the Channel to the Kn Service, and set the `replyTo` attribute on that Subscription to wherever the response should be routed.

Our authoring tool https://github.com/triggermesh/til does that automatically for you, but if you manipulate YAML directly you need to interpolate those two objects yourself.

**Comment by antoineco** [comment]
Example:

```hcl
# my-bridge.brg.hcl

router content_based "dispatch" {
  route {
    to = transformer.custom_tsf
  }
}

transformer function "custom_tsf" {
  runtime = "python"

  code = <<EOF
   def main(payload, context):
        payload['metdata'] = 'some change'

        return payload
  EOF

  ce_context {
    type = "my.transformation.v1.event"
  }

  public = true

  to = target.example_inner
}

target container "example_inner" {
  image = "registry.example.com/myapp:v1"

  reply_to = router.dispatch
}
```

Generated YAML.
Notice the Channel and Subscription objects:

```yaml
apiVersion: extensions.triggermesh.io/v1alpha1
kind: Function
metadata:
  labels:
    bridges.triggermesh.io/id: til_generated
  name: custom-tsf
spec:
  ceOverrides:
    extensions:
      type: my.transformation.v1.event
  code: |2
      def main(payload, context):
          payload['metdata'] = 'some change'
          return payload
  entrypoint: main
  public: true
  runtime: python
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: example-inner
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  labels:
    bridges.triggermesh.io/id: til_generated
  name: dispatch
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  labels:
    bridges.triggermesh.io/id: til_generated
  name: dispatch-r0
spec:
  broker: dispatch
  subscriber:
    ref:
      apiVersion: extensions.triggermesh.io/v1alpha1
      kind: Function
      name: custom-tsf
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    bridges.triggermesh.io/id: til_generated
    networking.knative.dev/visibility: cluster-local
  name: example-inner
spec:
  template:
    spec:
      containers:
      - image: registry.example.com/myapp:v1
---
apiVersion: messaging.knative.dev/v1
kind: Channel
metadata:
  labels:
    bridges.triggermesh.io/id: til_generated
  name: example-inner
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  labels:
    bridges.triggermesh.io/id: til_generated
  name: example-inner
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: example-inner
  reply:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: dispatch
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: example-inner
```
